name: dvc-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          # Install requirements 
          pip install --upgrade pip
          pip install -r requirements.txt

          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull data
          dvc repro -f
          
          # Report metrics 
          
          echo "## Validating results" >> report.md
          git fetch --prune
          dvc metrics diff titanic-test --show-md  >> report.md

          # Send results
          cml-send-comment report.md 